# Generated by Django 3.2.18 on 2023-03-19 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='SLUG')),
            ],
        ),
        migrations.CreateModel(
            name='CPUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование ЦПУ')),
                ('socket', models.CharField(max_length=10, verbose_name='Сокет')),
                ('count_core', models.IntegerField(verbose_name='Количество ядер')),
                ('count_threads', models.IntegerField(verbose_name='Количество потоков')),
                ('value', models.FloatField(verbose_name='Частота процессора')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Буст процессора')),
            ],
        ),
        migrations.CreateModel(
            name='data_drives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('memory', models.IntegerField(verbose_name='Количество памяти')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('socket', models.CharField(max_length=10, verbose_name='Сокет')),
            ],
        ),
        migrations.CreateModel(
            name='Oper_System_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('type', models.CharField(max_length=10, verbose_name='Тип')),
                ('memory', models.IntegerField(verbose_name='Память на 1 плашку')),
            ],
        ),
        migrations.CreateModel(
            name='video_cards_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Тип видеокарты')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('memory', models.IntegerField(blank=True, null=True, verbose_name='Количество памяти')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='Частота работы видеочипа')),
                ('max_value', models.IntegerField(blank=True, null=True, verbose_name='Турбочастота')),
                ('type_memory', models.CharField(blank=True, max_length=15, null=True, verbose_name='Тип памяти')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.video_cards_type', verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='SLUG')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('src', models.CharField(max_length=255, null=True)),
                ('count_ram', models.IntegerField(default=1, verbose_name='Количество оперативной памяти')),
                ('count_data', models.IntegerField(default=1, verbose_name='Количество накопителей данных')),
                ('garant', models.IntegerField(verbose_name='Гарантия в мес.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.category', verbose_name='Категория')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.cpus', verbose_name='ЦПУ')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.data_drives', verbose_name='Накопитель данных')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.motherboard', verbose_name='Материнская плата')),
                ('oc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.oper_system_type', verbose_name='Операционная система')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.ram', verbose_name='ОЗУ')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.video_cards', verbose_name='Видеокарта')),
            ],
        ),
        migrations.CreateModel(
            name='Orders_PCs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SitePC.orders')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SitePC.pc')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='models', through='SitePC.Orders_PCs', to='SitePC.PC'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
