# Generated by Django 3.2.18 on 2023-03-03 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='CPUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('socket', models.CharField(max_length=10)),
                ('count_core', models.IntegerField()),
                ('count_threads', models.IntegerField()),
                ('value', models.FloatField()),
                ('max_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='data_drives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('memory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('socket', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Oper_System_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('memory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='video_cards_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Video_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('memory', models.IntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('type_memory', models.CharField(blank=True, max_length=15, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.video_cards_type')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('components', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('price', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('src', models.CharField(max_length=255, null=True)),
                ('garant', models.IntegerField()),
                ('count_ram', models.IntegerField(default=1)),
                ('count_data', models.IntegerField(default=1)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.category')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.cpus')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.data_drives')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.motherboard')),
                ('oc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.oper_system_type')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.ram')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.video_cards')),
            ],
        ),
    ]
