# Generated by Django 4.1.7 on 2023-02-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitePC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='components',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
