# Generated by Django 3.2.18 on 2023-03-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitePC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_pcs',
            name='count',
            field=models.IntegerField(verbose_name='Количество товара'),
        ),
    ]
