# Generated by Django 3.2.18 on 2023-03-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SitePC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='components',
        ),
    ]
