# Generated by Django 3.2.18 on 2023-03-03 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SitePC', '0002_remove_pc_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='SLUG'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='count_core',
            field=models.IntegerField(verbose_name='Количество ядер'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='count_threads',
            field=models.IntegerField(verbose_name='Количество потоков'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='max_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Буст процессора'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='socket',
            field=models.CharField(max_length=10, verbose_name='Сокет'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Наименование ЦПУ'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='value',
            field=models.FloatField(verbose_name='Частота процессора'),
        ),
        migrations.AlterField(
            model_name='data_drives',
            name='memory',
            field=models.IntegerField(verbose_name='Количество памяти'),
        ),
        migrations.AlterField(
            model_name='data_drives',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='socket',
            field=models.CharField(max_length=10, verbose_name='Сокет'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='oper_system_type',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='count_data',
            field=models.IntegerField(default=1, verbose_name='Количество накопителей данных'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='count_ram',
            field=models.IntegerField(default=1, verbose_name='Количество оперативной памяти'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.cpus', verbose_name='ЦПУ'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.data_drives', verbose_name='Накопитель данных'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='garant',
            field=models.IntegerField(verbose_name='Гарантия в мес.'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.motherboard', verbose_name='Материнская плата'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='oc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.oper_system_type', verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='price',
            field=models.CharField(max_length=25, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.ram', verbose_name='ОЗУ'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='SLUG'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.video_cards', verbose_name='Видеокарта'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='memory',
            field=models.IntegerField(verbose_name='Память на 1 плашку'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='type',
            field=models.CharField(max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='video_cards',
            name='max_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Турбочастота'),
        ),
        migrations.AlterField(
            model_name='video_cards',
            name='memory',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество памяти'),
        ),
        migrations.AlterField(
            model_name='video_cards',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='video_cards',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SitePC.video_cards_type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='video_cards',
            name='type_memory',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Тип памяти'),
        ),
        migrations.AlterField(
            model_name='video_cards',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Частота работы видеочипа'),
        ),
        migrations.AlterField(
            model_name='video_cards_type',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Тип видеокарты'),
        ),
    ]
